apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-with-presync
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/mihai-tracer/argocd-test.git
    targetRevision: main
    path: app-with-presync
    helm:
      valuesObject:
        image:
          tag: "3.22.2"
        cm:
          someValue: cm-value-v1
