# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: alpine
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "3.22.2"

nameOverride: ""
fullnameOverride: ""

cm:
  someValue: cm-value-v1

preSyncJob:
  someEnvVar: job-env-var-v1
