apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "app-with-presync.fullname" . }}
  labels:
    {{- include "app-with-presync.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-options: Force=true,Replace=true
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/hook: "PreSync"
    argocd.argoproj.io/sync-wave: "-100"
spec:
  template:
    metadata:
      labels:
        {{- include "app-with-presync.labels" . | nindent 8 }}
    spec:
      containers:
        - name: fancy-db-migrations
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["sh"]
          args: ["-c", "echo $(SOME_ENV_VAR) && sleep 3"]
          env:
            - name: SOME_ENV_VAR
              value: {{ .Values.preSyncJob.someEnvVar | quote }}
          terminationMessagePolicy: FallbackToLogsOnError
          terminationMessagePath: /dev/termination-log
      restartPolicy: OnFailure
